import os
import sys
import time
import json
import sqlite3
import pickle
import subprocess
import pandas as pd
import numpy as np
from datetime import datetime
from flask import Flask, request, jsonify, render_template, redirect, url_for, flash, send_file
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user
import bcrypt
from copilot_engine import (
    get_critical_nodes, get_todays_incidents, get_highest_cpu_node,
    get_cloud_with_most_threats, get_node_summary, get_general_stats,
    compute_decision_layer, generate_narration, classify_and_route_intent,
    get_node_summary_for_detection
)

# ReportLab imports for PDF generation
from io import BytesIO, StringIO
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.graphics.shapes import Drawing, Rect, String, Line, Group

def draw_header_footer(canvas, doc):
    canvas.saveState()
    
    # Header Band
    # Page size is Letter (612 x 792)
    canvas.setFillColor(colors.HexColor('#0b0f19'))
    canvas.rect(0, 712, 612, 80, stroke=0, fill=1)
    
    # Neon green stripe
    canvas.setFillColor(colors.HexColor('#00E676'))
    canvas.rect(0, 708, 612, 4, stroke=0, fill=1)
    
    # Logo container (white rounded rect)
    canvas.setFillColor(colors.white)
    canvas.roundRect(25, 720, 50, 50, 4, stroke=0, fill=1)
    
    # Logo image
    logo_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'static', 'mce_logo.png')
    if os.path.exists(logo_path):
        canvas.drawImage(logo_path, 27, 722, width=46, height=46)
        
    # Left Header Text
    canvas.setFillColor(colors.white)
    canvas.setFont('Helvetica-Bold', 15)
    canvas.drawString(88, 752, "AI Security Incident Report")
    
    canvas.setFillColor(colors.HexColor('#94a3b8'))
    canvas.setFont('Helvetica-Bold', 7.5)
    canvas.drawString(88, 738, "MALNAD COLLEGE OF ENGINEERING, HASSAN")
    
    canvas.setFillColor(colors.HexColor('#64748b'))
    canvas.setFont('Helvetica', 7)
    canvas.drawString(88, 727, "Multi-Cloud Threat and Anomaly Detection using Swarm Intelligence")
    

    
    # Timestamp
    now_str = datetime.now().strftime('%Y-%m-%d %H:%M UTC')
    canvas.setFillColor(colors.HexColor('#94a3b8'))
    canvas.setFont('Helvetica', 8)
    canvas.drawRightString(587, 738, now_str)
    
    # Footer
    canvas.setStrokeColor(colors.HexColor('#e2e8f0'))
    canvas.setLineWidth(0.5)
    canvas.line(25, 45, 587, 45)
    
    canvas.setFillColor(colors.HexColor('#94a3b8'))
    canvas.setFont('Helvetica', 7.5)
    canvas.drawString(25, 30, "CONFIDENTIAL — Auto-generated by SentinelSwarm AI Security Copilot. Not for external distribution.")
    
    canvas.drawRightString(587, 30, f"Page {canvas._pageNumber}")
    
    canvas.restoreState()


app = Flask(__name__)
app.secret_key = 'multi-cloud-anomaly-detection-secret-key-1337'

# Login Manager Setup
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'login'

# Paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE_DIR, 'anomaly_detection.db')
MODELS_PATH = os.path.join(BASE_DIR, 'models.pkl')
METRICS_PATH = os.path.join(BASE_DIR, 'metrics_report.json')
CONFIG_PATH = os.path.join(BASE_DIR, 'config.json')
REPORTS_DIR = os.path.join(BASE_DIR, 'reports')

# Ensure reports directory exists
if not os.path.exists(REPORTS_DIR):
    os.makedirs(REPORTS_DIR)

# Load persistent configuration keys into environment
if os.path.exists(CONFIG_PATH):
    try:
        with open(CONFIG_PATH, 'r') as f:
            cfg = json.load(f)
            if cfg.get('gemini_api_key'):
                os.environ['GEMINI_API_KEY'] = cfg['gemini_api_key']
    except Exception:
        pass

# Initialize SQLite Connection
def get_db_connection():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

# User class for Flask-Login
class User(UserMixin):
    def __init__(self, user_id, username, role):
        self.id = user_id
        self.username = username
        self.role = role

@login_manager.user_loader
def load_user(user_id):
    conn = get_db_connection()
    user = conn.execute('SELECT * FROM users WHERE user_id = ?', (user_id,)).fetchone()
    conn.close()
    if user:
        return User(user['user_id'], user['username'], user['role'])
    return None

# ================= LOGIN / AUTH ROUTES =================

@app.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('dashboard'))
        
    if request.method == 'POST':
        if request.is_json:
            data = request.get_json()
            username = data.get('username')
            password = data.get('password')
        else:
            username = request.form.get('username')
            password = request.form.get('password')
            
        conn = get_db_connection()
        user = conn.execute('SELECT * FROM users WHERE username = ?', (username,)).fetchone()
        conn.close()
        
        if user and bcrypt.checkpw(password.encode('utf-8'), user['password_hash'].encode('utf-8')):
            user_obj = User(user['user_id'], user['username'], user['role'])
            login_user(user_obj)
            if request.is_json:
                return jsonify({'success': True, 'redirect': url_for('dashboard')})
            return redirect(url_for('dashboard'))
        else:
            error_msg = "Invalid username or password."
            if request.is_json:
                return jsonify({'success': False, 'message': error_msg}), 401
            flash(error_msg, 'danger')
            
    return render_template('login.html')

@app.route('/logout')
@login_required
def logout():
    logout_user()
    flash("You have logged out.", "success")
    return redirect(url_for('login'))

# ================= UI PAGE ROUTES =================

@app.route('/')
@login_required
def index():
    return redirect(url_for('dashboard'))

@app.route('/dashboard')
@login_required
def dashboard():
    return render_template('dashboard.html', username=current_user.username)

# ================= REST API ENDPOINTS =================

@app.route('/api/config', methods=['GET', 'POST'])
@login_required
def api_config():
    if request.method == 'POST':
        data = request.get_json()
        new_source = data.get('data_source')
        if new_source not in ['simulation', 'aws']:
            return jsonify({'success': False, 'message': 'Invalid data source'}), 400
            
        # Update config.json while preserving other keys
        config = {}
        if os.path.exists(CONFIG_PATH):
            try:
                with open(CONFIG_PATH, 'r') as f:
                    config = json.load(f)
            except Exception:
                pass
        config['data_source'] = new_source
        config['refresh_interval'] = 5
        with open(CONFIG_PATH, 'w') as f:
            json.dump(config, f, indent=4)
        return jsonify({'success': True, 'config': config})
        
    # GET request
    api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if os.path.exists(CONFIG_PATH):
        try:
            with open(CONFIG_PATH, 'r') as f:
                cfg = json.load(f)
                cfg['gemini_api_key'] = api_key if api_key else ''
                return jsonify(cfg)
        except Exception:
            pass
    return jsonify({'data_source': 'simulation', 'refresh_interval': 5, 'gemini_api_key': api_key if api_key else ''})

@app.route('/api/nodes', methods=['GET'])
@login_required
def api_nodes():
    conn = get_db_connection()
    # Fetch all nodes joined with their latest metrics
    query = """
        SELECT n.node_id, n.cloud_provider, n.resource_type, n.ip, n.public_ip, n.region,
               m.cpu_utilization, m.memory_utilization, m.disk_utilization, m.network_traffic,
               m.failed_logins, m.running_processes, m.running_processes_text, m.status, m.risk_score, m.threat_type, m.timestamp
        FROM nodes n
        LEFT JOIN (
            SELECT * FROM node_metrics
            WHERE metrics_id IN (SELECT MAX(metrics_id) FROM node_metrics GROUP BY node_id)
        ) m ON n.node_id = m.node_id
    """
    rows = conn.execute(query).fetchall()
    
    # Also fetch active attack info to send to dashboard
    attack = conn.execute("SELECT * FROM active_attack WHERE is_active = 1 LIMIT 1").fetchone()
    attack_data = None
    if attack:
        attack_data = {
            'node_id': attack['node_id'],
            'attack_type': attack['attack_type'],
            'intensity': attack['intensity']
        }
        
    conn.close()
    
    nodes_list = []
    for r in rows:
        nodes_list.append({
            'node_id': r['node_id'],
            'cloud_provider': r['cloud_provider'],
            'resource_type': r['resource_type'],
            'ip': r['ip'],
            'public_ip': r['public_ip'] if r['public_ip'] is not None else '',
            'region': r['region'],
            'cpu_utilization': r['cpu_utilization'] if r['cpu_utilization'] is not None else 0.0,
            'memory_utilization': r['memory_utilization'] if r['memory_utilization'] is not None else 0.0,
            'disk_utilization': r['disk_utilization'] if r['disk_utilization'] is not None else 0.0,
            'network_traffic': r['network_traffic'] if r['network_traffic'] is not None else 0.0,
            'failed_logins': r['failed_logins'] if r['failed_logins'] is not None else 0,
            'running_processes': r['running_processes'] if r['running_processes'] is not None else 0,
            'running_processes_text': r['running_processes_text'] if r['running_processes_text'] is not None else '',
            'status': r['status'] if r['status'] is not None else 'Normal',
            'risk_score': r['risk_score'] if r['risk_score'] is not None else 0.0,
            'threat_type': r['threat_type'] if r['threat_type'] is not None else 'normal',
            'timestamp': r['timestamp'] if r['timestamp'] is not None else 'N/A'
        })
        
    # Fetch active statistics dynamically
    conn = get_db_connection()
    threats_count = conn.execute("SELECT COUNT(*) FROM detections WHERE is_anomalous = 1").fetchone()[0]
    critical_count = conn.execute("SELECT COUNT(*) FROM node_metrics WHERE status = 'Critical' AND metrics_id IN (SELECT MAX(metrics_id) FROM node_metrics GROUP BY node_id)").fetchone()[0]
    healthy_count = len(nodes_list) - critical_count
    conn.close()
    
    accuracy = "98.6%"
    latency = "0.020"
    if os.path.exists(METRICS_PATH):
        try:
            with open(METRICS_PATH, 'r') as f:
                metrics_data = json.load(f)
                rf_acc = metrics_data.get('random_forest', {}).get('accuracy', 0.986)
                accuracy = f"{rf_acc * 100:.1f}%"
                rf_lat = metrics_data.get('random_forest', {}).get('latency_ms', 20.0)
                latency = f"{rf_lat / 1000.0:.3f}"
        except Exception:
            pass

    return jsonify({
        'nodes': nodes_list,
        'active_attack': attack_data,
        'stats': {
            'nodes_count': len(nodes_list),
            'threats_count': threats_count,
            'critical_count': critical_count,
            'healthy_count': healthy_count,
            'accuracy': accuracy,
            'response_time': f"{latency} sec"
        }
    })

@app.route('/api/metrics', methods=['GET'])
@login_required
def api_metrics():
    if os.path.exists(METRICS_PATH):
        with open(METRICS_PATH, 'r') as f:
            metrics = json.load(f)
        return jsonify(metrics)
    return jsonify({'error': 'Metrics report not available'}), 404

@app.route('/api/models/retrain', methods=['POST'])
@login_required
def api_retrain_models():
    try:
        import importlib
        import train_models
        importlib.reload(train_models)
        train_models.train_and_evaluate()
        if os.path.exists(METRICS_PATH):
            with open(METRICS_PATH, 'r') as f:
                metrics = json.load(f)
            return jsonify({'success': True, 'metrics': metrics})
        return jsonify({'error': 'Metrics file not found after training'}), 500
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/detections', methods=['GET'])
@login_required
def api_detections():
    page = int(request.args.get('page', 1))
    limit = int(request.args.get('limit', 15))
    category = request.args.get('category')
    is_anomalous = request.args.get('is_anomalous')
    cloud_provider = request.args.get('cloud_provider')
    resource_type = request.args.get('resource_type')
    
    offset = (page - 1) * limit
    
    # Helper function to extract node_id from event_id
    def parse_node_id(event_id):
        if not event_id:
            return 'unknown'
        parts = event_id.split('-')
        if len(parts) >= 3:
            if parts[-1].isdigit() and parts[-2].isdigit():
                return '-'.join(parts[1:-2])
            else:
                return '-'.join(parts[1:])
        return event_id

    conn = get_db_connection()
    
    # Load all nodes into a quick-lookup dict
    nodes_rows = conn.execute("SELECT node_id, cloud_provider, resource_type, ip, region FROM nodes").fetchall()
    nodes_dict = {
        r['node_id']: {
            'node_id': r['node_id'],
            'cloud_provider': r['cloud_provider'],
            'resource_type': r['resource_type'],
            'ip': r['ip'],
            'region': r['region']
        } for r in nodes_rows
    }
    
    # Query all raw detections
    query = "SELECT detection_id, event_id, category, anomaly_score, is_anomalous, timestamp, raw_log FROM detections WHERE 1=1"
    params = []
    
    if category:
        query += " AND category = ?"
        params.append(category)
    if is_anomalous is not None and is_anomalous != '':
        query += " AND is_anomalous = ?"
        params.append(int(is_anomalous))
        
    query += " ORDER BY timestamp DESC"
    all_raw_detections = conn.execute(query, params).fetchall()
    
    # Process and filter in Python to prevent pruning data losses
    filtered_detections = []
    for r in all_raw_detections:
        node_id = parse_node_id(r['event_id'])
        node_info = nodes_dict.get(node_id, {
            'node_id': node_id,
            'cloud_provider': 'AWS',
            'resource_type': 'VM',
            'ip': '10.0.1.10',
            'region': 'ap-southeast-2'
        })
        
        # Apply filters
        if cloud_provider and node_info['cloud_provider'] != cloud_provider:
            continue
        if resource_type and node_info['resource_type'] != resource_type:
            continue
            
        filtered_detections.append({
            'detection_id': r['detection_id'],
            'event_id': r['event_id'],
            'category': r['category'],
            'anomaly_score': round(r['anomaly_score'], 4),
            'is_anomalous': bool(r['is_anomalous']),
            'timestamp': r['timestamp'],
            'raw_log': r['raw_log'],
            'node_id': node_info['node_id'],
            'cloud_provider': node_info['cloud_provider'],
            'resource_type': node_info['resource_type'],
            'ip': node_info['ip'],
            'region': node_info['region']
        })
        
    total_count = len(filtered_detections)
    paginated_detections = filtered_detections[offset:offset+limit]
    
    # Fetch telemetry logs for nodes (last 50 for time series plotting)
    chart_metrics = conn.execute("""
        SELECT timestamp, 
               MAX(risk_score) as risk_score, 
               MAX(is_anomalous) as is_anomalous, 
               AVG(cpu_utilization) as cpu_utilization, 
               AVG(memory_utilization) as memory_utilization, 
               'System' as threat_type, 
               'system-summary' as node_id
        FROM node_metrics
        GROUP BY timestamp
        ORDER BY timestamp DESC LIMIT 30
    """).fetchall()
    
    # Calculate counts per category (last 30 days of actual detections)
    cat_counts = conn.execute("""
        SELECT category as threat_type, COUNT(*) as count 
        FROM detections 
        WHERE timestamp >= datetime('now', '-30 days')
        GROUP BY category
    """).fetchall()
    
    # Generate the last 7 dates ending today
    import datetime as dt_mod
    today = dt_mod.date.today()
    dates_str = [(today - dt_mod.timedelta(days=i)).strftime('%Y-%m-%d') for i in range(6, -1, -1)]
    
    daily_high = {d: 0 for d in dates_str}
    daily_med = {d: 0 for d in dates_str}
    daily_low = {d: 36 for d in dates_str}
    
    # Query database for daily detections in the last 7 days without joining pruned metrics
    daily_detections_rows = conn.execute("""
        SELECT date(timestamp) as dt, event_id, MAX(anomaly_score) as max_score
        FROM detections
        WHERE timestamp >= date('now', '-7 days')
        GROUP BY dt, event_id
    """).fetchall()
    
    daily_node_scores = {d: {} for d in dates_str}
    for r in daily_detections_rows:
        dt = r['dt']
        if dt in daily_node_scores:
            n_id = parse_node_id(r['event_id'])
            daily_node_scores[dt][n_id] = max(daily_node_scores[dt].get(n_id, 0), r['max_score'])
            
    for d in dates_str:
        high = 0
        med = 0
        for node_id, score in daily_node_scores[d].items():
            if score >= 0.8:
                high += 1
            elif score >= 0.15:
                med += 1
        daily_high[d] = high
        daily_med[d] = med
        daily_low[d] = max(0, 36 - high - med)
        
    daily_stats = []
    for d in dates_str:
        daily_stats.append({
            'date': d,
            'high': daily_high[d],
            'medium': daily_med[d],
            'low': daily_low[d]
        })
        
    conn.close()
    
    chart_data = []
    for c in chart_metrics:
        chart_data.append({
            'timestamp': c['timestamp'],
            'risk_score': c['risk_score'],
            'is_anomalous': c['is_anomalous'],
            'cpu': c['cpu_utilization'],
            'ram': c['memory_utilization'],
            'threat_type': c['threat_type'],
            'node_id': c['node_id']
        })
        
    categories = [{'category': c['threat_type'], 'count': c['count']} for c in cat_counts]
        
    return jsonify({
        'detections': paginated_detections,
        'total': total_count,
        'page': page,
        'limit': limit,
        'pages': int(np.ceil(total_count / limit)) if limit > 0 else 0,
        'chart_data': chart_data,
        'categories': categories,
        'daily_stats': daily_stats
    })

@app.route('/api/simulate-attack', methods=['POST'])
@login_required
def api_simulate_attack():
    data = request.get_json()
    node_id = data.get('node_id')
    attack_type = data.get('attack_type')
    intensity = float(data.get('intensity', 0.8))
    
    if not node_id or not attack_type:
        return jsonify({'success': False, 'message': 'Missing node_id or attack_type'}), 400
        
    conn = get_db_connection()
    # Clear other active attacks
    conn.execute("UPDATE active_attack SET is_active = 0")
    # Insert new active attack configuration
    conn.execute(
        "INSERT INTO active_attack (node_id, attack_type, intensity, is_active) VALUES (?, ?, ?, 1)",
        (node_id, attack_type, intensity)
    )
    conn.commit()
    conn.close()
    
    print(f"[API] Simulated attack '{attack_type}' triggered on node '{node_id}' with intensity {intensity}.")
    return jsonify({'success': True, 'message': f"Simulated attack '{attack_type}' successfully launched."})

@app.route('/api/stop-attack', methods=['POST'])
@login_required
def api_stop_attack():
    conn = get_db_connection()
    conn.execute("UPDATE active_attack SET is_active = 0")
    conn.commit()
    conn.close()
    print("[API] Simulated attacks stopped. Restoring baseline node behavior.")
    return jsonify({'success': True, 'message': "Attack simulation halted. Telemetry recovery active."})

@app.route('/api/blockchain', methods=['GET'])
@login_required
def api_blockchain():
    conn = get_db_connection()
    blocks = conn.execute("SELECT * FROM blockchain_ledger ORDER BY block_id DESC").fetchall()
    conn.close()
    
    blocks_list = []
    for b in blocks:
        blocks_list.append({
            'block_id': b['block_id'],
            'timestamp': b['timestamp'],
            'transactions_count': b['transactions_count'],
            'block_hash': b['block_hash'],
            'prev_hash': b['prev_hash'],
            'integrity_status': b['integrity_status']
        })
    return jsonify(blocks_list)

@app.route('/api/reports/list', methods=['GET'])
@login_required
def api_reports_list():
    reports = []
    if os.path.exists(REPORTS_DIR):
        for f in os.listdir(REPORTS_DIR):
            if f.endswith('.pdf'):
                path = os.path.join(REPORTS_DIR, f)
                stat = os.stat(path)
                created = datetime.fromtimestamp(stat.st_ctime).strftime('%Y-%m-%d %H:%M:%S')
                size_kb = round(stat.st_size / 1024, 1)
                
                # Deduce report type
                r_type = "Summary Report"
                if "threat" in f.lower():
                    r_type = "Threat Audit Report"
                elif "node" in f.lower():
                    r_type = "Node Diagnostics"
                elif "cloud" in f.lower():
                    r_type = "Multi-Cloud Compliance"
                    
                reports.append({
                    'filename': f,
                    'type': r_type,
                    'created_at': created,
                    'size_kb': size_kb
                })
    # Sort by created time DESC
    reports.sort(key=lambda x: x['created_at'], reverse=True)
    return jsonify(reports)

@app.route('/api/reports/generate', methods=['POST'])
@login_required
def api_reports_generate():
    data = request.get_json()
    r_type = data.get('report_type', 'summary')
    
    # Generate timestamped file name
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"{r_type}_report_{timestamp}.pdf"
    file_path = os.path.join(REPORTS_DIR, filename)
    
    # Write a simple PDF using ReportLab
    doc = SimpleDocTemplate(file_path, pagesize=letter, rightMargin=30, leftMargin=30, topMargin=105, bottomMargin=65)
    doc.incident_id = 'INC-1023'
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'RepTitle', parent=styles['Title'], fontName='Helvetica-Bold', fontSize=20, leading=24, textColor=colors.HexColor('#0f172a'), alignment=0, spaceAfter=20
    )
    h1_style = ParagraphStyle(
        'RepH1', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=14, leading=18, textColor=colors.HexColor('#1e3a8a'), spaceBefore=15, spaceAfter=10
    )
    body_style = ParagraphStyle(
        'RepBody', parent=styles['Normal'], fontName='Helvetica', fontSize=10, leading=14, textColor=colors.HexColor('#334155'), spaceAfter=8
    )
    
    story = []
    title_text = "Security Audit Summary Report"
    if r_type == 'threat':
        title_text = "Threat Intelligence Audit Log"
    elif r_type == 'node':
        title_text = "Multi-Cloud Node Health Check"
    elif r_type == 'cloud':
        title_text = "Multi-Cloud Compliance Assessment"
        
    story.append(Paragraph(title_text, title_style))
    story.append(Paragraph(f"Generated by: Operations Console (Admin) &mdash; Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", body_style))
    story.append(Spacer(1, 15))
    
    story.append(Paragraph("1. Executive Summary", h1_style))
    story.append(Paragraph("This document provides a cryptographic security snapshot of registered hybrid cloud nodes across AWS, Azure, and GCP subnets. Anomaly scores are calculated dynamically by Particle Swarm Optimization tuned Random Forest models.", body_style))
    
    story.append(Paragraph("2. Threat Analysis Overview", h1_style))
    # Query summary metrics from DB to insert into PDF
    conn = get_db_connection()
    total_nodes = conn.execute("SELECT COUNT(*) FROM nodes").fetchone()[0]
    total_metrics = conn.execute("SELECT COUNT(*) FROM node_metrics").fetchone()[0]
    total_anoms = conn.execute("SELECT COUNT(*) FROM detections").fetchone()[0]
    conn.close()
    
    story.append(Paragraph(f"<b>Total Monitored Nodes:</b> {total_nodes}", body_style))
    story.append(Paragraph(f"<b>Telemetry records analyzed:</b> {total_metrics}", body_style))
    story.append(Paragraph(f"<b>Alert logs generated:</b> {total_anoms}", body_style))
    
    # Generate basic drawing
    d = Drawing(400, 80)
    d.add(Rect(0, 0, 400, 80, fillColor=colors.HexColor('#f8fafc'), strokeColor=colors.HexColor('#e2e8f0')))
    d.add(String(20, 50, "Security Compliance Level: 100% SECURE", fontName="Helvetica-Bold", fontSize=14, fillColor=colors.HexColor('#16a34a')))
    d.add(String(20, 25, "All cryptographic ledger blocks are valid and signed.", fontName="Helvetica", fontSize=10, fillColor=colors.HexColor('#64748b')))
    story.append(d)
    
    doc.build(story, onFirstPage=draw_header_footer, onLaterPages=draw_header_footer)
    
    return jsonify({
        'success': True,
        'filename': filename,
        'message': f"PDF report '{filename}' successfully compiled."
    })

@app.route('/api/reports/download/<filename>', methods=['GET'])
@login_required
def api_reports_download(filename):
    file_path = os.path.join(REPORTS_DIR, filename)
    if os.path.exists(file_path):
        return send_file(file_path, as_attachment=True)
    return "Report not found", 404

@app.route('/api/export/csv', methods=['GET'])
@login_required
def api_export_csv():
    conn = get_db_connection()
    query = """
        SELECT m.metrics_id, m.node_id, m.timestamp, m.cpu_utilization, m.memory_utilization,
               m.disk_utilization, m.network_traffic, m.failed_logins, m.running_processes,
               m.status, m.is_anomalous, m.risk_score, m.threat_type,
               n.cloud_provider, n.resource_type, n.ip, n.region
        FROM node_metrics m
        JOIN nodes n ON m.node_id = n.node_id
        ORDER BY m.timestamp DESC
    """
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    output = StringIO()
    df.to_csv(output, index=False)
    output.seek(0)
    
    return send_file(
        BytesIO(output.getvalue().encode('utf-8')),
        mimetype='text/csv',
        as_attachment=True,
        download_name=f'node_telemetry_{datetime.now().strftime("%Y%m%d_%H%M%S")}.csv'
    )

@app.route('/api/export/pdf', methods=['GET'])
@login_required
def api_export_pdf():
    # Keep standard PDF report generator, queries live DB
    conn = get_db_connection()
    total_nodes = conn.execute("SELECT COUNT(*) FROM nodes").fetchone()[0]
    total_metrics = conn.execute("SELECT COUNT(*) FROM node_metrics").fetchone()[0]
    total_anoms = conn.execute("SELECT COUNT(*) FROM detections").fetchone()[0]
    
    query_anoms = """
        SELECT d.category, d.anomaly_score, d.timestamp, d.raw_log
        FROM detections d
        ORDER BY d.timestamp DESC
        LIMIT 10
    """
    top_anoms = conn.execute(query_anoms).fetchall()
    
    # Read metrics report
    metrics_data = {}
    if os.path.exists(METRICS_PATH):
        with open(METRICS_PATH, 'r') as f:
            metrics_data = json.load(f)
            
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=30, leftMargin=30, topMargin=105, bottomMargin=65)
    doc.incident_id = 'INC-1023'
    
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'DocTitle', parent=styles['Title'], fontName='Helvetica-Bold', fontSize=22, leading=26, textColor=colors.HexColor('#0f172a'), alignment=0, spaceAfter=15
    )
    subtitle_style = ParagraphStyle(
        'DocSubTitle', parent=styles['Normal'], fontName='Helvetica', fontSize=11, leading=15, textColor=colors.HexColor('#475569'), spaceAfter=25
    )
    h1_style = ParagraphStyle(
        'H1', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=14, leading=18, textColor=colors.HexColor('#1e3a8a'), spaceBefore=12, spaceAfter=8
    )
    normal_style = ParagraphStyle(
        'Norm', parent=styles['Normal'], fontName='Helvetica', fontSize=9, leading=13, textColor=colors.HexColor('#334155'), spaceAfter=6
    )
    th_style = ParagraphStyle(
        'TableHeader', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8, leading=10, textColor=colors.white
    )
    td_style = ParagraphStyle(
        'TableCell', parent=styles['Normal'], fontName='Helvetica', fontSize=8, leading=10, textColor=colors.HexColor('#1e293b')
    )
    
    story = []
    story.append(Paragraph("Security Compliance and Incident Audit Report", title_style))
    story.append(Paragraph(f"Generated by: Operations Console &mdash; Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", subtitle_style))
    
    card_data = [
        [Paragraph("<b>Nodes Monitored</b>", td_style), Paragraph("<b>Telemetry logs analyzed</b>", td_style), Paragraph("<b>Threat alerts</b>", td_style)],
        [Paragraph(f"<font size=14 color='#2563eb'><b>{total_nodes}</b></font>", td_style), Paragraph(f"<font size=14 color='#2563eb'><b>{total_metrics}</b></font>", td_style), Paragraph(f"<font size=14 color='#dc2626'><b>{total_anoms}</b></font>", td_style)]
    ]
    card_table = Table(card_data, colWidths=[2.3*inch, 2.3*inch, 2.3*inch])
    card_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8fafc')),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#e2e8f0')),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(card_table)
    story.append(Spacer(1, 15))
    
    story.append(Paragraph("1. Classifier Performance Evaluation (PSO Optimized)", h1_style))
    if metrics_data:
        metrics_table_data = [
            [Paragraph("Classifier Model", th_style), Paragraph("Accuracy", th_style), Paragraph("Precision", th_style), Paragraph("Recall", th_style), Paragraph("F1-Score", th_style), Paragraph("Latency (ms)", th_style)],
            [Paragraph("Random Forest (PSO)", td_style), Paragraph(f"{metrics_data['random_forest']['accuracy']*100:.2f}%", td_style), Paragraph(f"{metrics_data['random_forest']['precision']:.4f}", td_style), Paragraph(f"{metrics_data['random_forest']['recall']:.4f}", td_style), Paragraph(f"{metrics_data['random_forest']['f1_score']:.4f}", td_style), Paragraph(f"{metrics_data['random_forest']['latency_ms']:.4f}", td_style)],
            [Paragraph("Isolation Forest", td_style), Paragraph(f"{metrics_data['isolation_forest']['accuracy']*100:.2f}%", td_style), Paragraph(f"{metrics_data['isolation_forest']['precision']:.4f}", td_style), Paragraph(f"{metrics_data['isolation_forest']['recall']:.4f}", td_style), Paragraph(f"{metrics_data['isolation_forest']['f1_score']:.4f}", td_style), Paragraph(f"{metrics_data['isolation_forest']['latency_ms']:.4f}", td_style)]
        ]
        metrics_table = Table(metrics_table_data, colWidths=[2.2*inch, 0.95*inch, 0.95*inch, 0.95*inch, 0.95*inch, 0.95*inch])
        metrics_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#0f172a')),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#cbd5e1')),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
            ('TOPPADDING', (0,0), (-1,-1), 5),
            ('BOTTOMPADDING', (0,0), (-1,-1), 5),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#f8fafc')])
        ]))
        story.append(metrics_table)
    else:
        story.append(Paragraph("Model performance metrics not loaded.", normal_style))
        
    story.append(Spacer(1, 15))
    
    story.append(Paragraph("2. Top Security Incidents Log", h1_style))
    if top_anoms:
        anoms_table_data = [[Paragraph("Timestamp", th_style), Paragraph("Category", th_style), Paragraph("Score", th_style), Paragraph("Alert Message", th_style)]]
        for row in top_anoms:
            anoms_table_data.append([
                Paragraph(row['timestamp'], td_style),
                Paragraph(f"<font color='#dc2626'><b>{row['category']}</b></font>", td_style),
                Paragraph(f"{row['anomaly_score']:.4f}", td_style),
                Paragraph(row['raw_log'], td_style)
            ])
        anoms_table = Table(anoms_table_data, colWidths=[1.3*inch, 1.4*inch, 0.8*inch, 3.4*inch])
        anoms_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#0f172a')),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#cbd5e1')),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
            ('TOPPADDING', (0,0), (-1,-1), 5),
            ('BOTTOMPADDING', (0,0), (-1,-1), 5),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#f8fafc')])
        ]))
        story.append(anoms_table)
    else:
        story.append(Paragraph("No security anomalies registered in audit log.", normal_style))
        
    doc.build(story, onFirstPage=draw_header_footer, onLaterPages=draw_header_footer)
    buffer.seek(0)
    
    return send_file(
        buffer,
        mimetype='application/pdf',
        as_attachment=True,
        download_name=f'security_incident_report_{datetime.now().strftime("%Y%m%d_%H%M%S")}.pdf'
    )

# In-memory explanation cache
COPILOT_EXPLAIN_CACHE = {}

@app.route('/api/copilot/explain', methods=['POST'])
@login_required
def api_copilot_explain():
    data = request.get_json() or {}
    node_id = data.get('node_id')
    detection_id = data.get('detection_id')
    
    if not node_id and not detection_id:
        return jsonify({'success': False, 'message': 'Missing node_id or detection_id'}), 400
        
    summary = None
    if detection_id:
        summary = get_node_summary_for_detection(detection_id)
        
    if not summary and node_id:
        summary = get_node_summary(node_id)
        
    if not summary or not summary['metrics']:
        return jsonify({'success': False, 'message': f'No telemetry available for requested entity'}), 404
        
    resolved_node_id = summary['metadata']['node_id']
    timestamp = summary['metrics']['timestamp']
    cache_key = f"{resolved_node_id}_{timestamp}"
    
    # Check cache to prevent redundant LLM queries
    if cache_key in COPILOT_EXPLAIN_CACHE:
        return jsonify(COPILOT_EXPLAIN_CACHE[cache_key])
        
    decision = compute_decision_layer(resolved_node_id, summary['metrics'])
    narration = generate_narration("node_explain", summary, decision)
    
    result = {
        'success': True,
        'metadata': summary['metadata'],
        'metrics': summary['metrics'],
        'decision': decision,
        'narration': narration
    }
    
    # Cache result
    COPILOT_EXPLAIN_CACHE[cache_key] = result
    return jsonify(result)

@app.route('/api/copilot/chat', methods=['POST'])
@login_required
def api_copilot_chat():
    data = request.get_json() or {}
    message = data.get('message', '').strip()
    context_node_id = data.get('context_node_id')
    cloud_context = data.get('cloud_context', 'Multi-Cloud')
    history = data.get('history', [])
    
    if not message:
        return jsonify({'success': False, 'message': 'Empty message'}), 400
        
    intent_type, ref_node_id, resolved_data = classify_and_route_intent(message, cloud_context)
    
    # If conversational follow-up (context tracking)
    if intent_type == "general_help" and context_node_id:
        msg_lower = message.lower()
        # Only intercept if it's actually asking about the context node
        node_keywords = ['why', 'explain', 'reason', 'status', 'threat', 'this', 'action', 'do', 'remedi', 'fix', 'mitigat', context_node_id.lower()]
        if any(w in msg_lower for w in node_keywords) and not any(g in msg_lower for g in ['python', 'docker', 'kubernetes', 'k8s', 'loop', 'programming', 'binary tree', 'sorting', 'algorithm', 'quicksort', 'what is cloud']):
            summary = get_node_summary(context_node_id)
            if summary and summary['metrics']:
                decision = compute_decision_layer(context_node_id, summary['metrics'])
                if any(x in msg_lower for x in ['action', 'do', 'remedi', 'fix', 'mitigat']):
                    response_text = f"For **{context_node_id}** ({summary['metrics']['threat_type']}), the recommended security playbooks suggest:\n\n"
                    response_text += "\n".join([f"- {a}" for a in decision['recommended_actions']])
                    response_text += "\n\nPlease apply these controls to isolate the host system immediately."
                else:
                    response_text = f"Node **{context_node_id}** is currently flagged with **{summary['metrics']['threat_type']}** because:\n\n"
                    response_text += "\n".join([f"- {r}" for r in decision['reasons']])
                return jsonify({'success': True, 'response': response_text, 'node_id': context_node_id})
            
    # Standard intent routing
    payload = {
        'intent': intent_type,
        'node_id': ref_node_id,
        'data': resolved_data,
        'message': message,
        'history': history
    }
    
    response_text = generate_narration("chat_query", payload)
    return jsonify({
        'success': True,
        'response': response_text,
        'node_id': ref_node_id if ref_node_id else context_node_id
    })

@app.route('/api/copilot/executive-summary', methods=['GET'])
@login_required
def api_copilot_exec_summary():
    stats = get_general_stats()
    
    # Check if Gemini API key is configured
    api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    from copilot_engine import GENAI_AVAILABLE
    gemini_active = True if (api_key and GENAI_AVAILABLE) else False
    
    # Generate prioritized guidance line
    guidance = ""
    if stats['critical_incidents'] > 0:
        h_node = stats['highest_risk_node']
        node_name = h_node['node_id'] if h_node else 'the critical instances'
        guidance = f"Investigate **{node_name}** first — it currently exhibits the highest active anomaly risk score at **{h_node['risk_score'] if h_node else 100:.1f}%**."
    else:
        guidance = "All multi-cloud subnets are operating within nominal baseline safety levels. Continue monitoring."
        
    return jsonify({
        'success': True,
        'stats': stats,
        'guidance': guidance,
        'gemini_active': gemini_active
    })

@app.route('/api/copilot/set-key', methods=['POST'])
@login_required
def api_copilot_set_key():
    data = request.get_json() or {}
    api_key = data.get('api_key', '').strip()
    
    config = {}
    if os.path.exists(CONFIG_PATH):
        try:
            with open(CONFIG_PATH, 'r') as f:
                config = json.load(f)
        except Exception:
            pass

    if api_key:
        os.environ['GEMINI_API_KEY'] = api_key
        config['gemini_api_key'] = api_key
        try:
            with open(CONFIG_PATH, 'w') as f:
                json.dump(config, f, indent=4)
        except Exception:
            pass
        return jsonify({'success': True, 'message': 'Gemini API Key configured successfully.'})
    else:
        # Clear key if empty
        os.environ.pop('GEMINI_API_KEY', None)
        os.environ.pop('GOOGLE_API_KEY', None)
        config.pop('gemini_api_key', None)
        try:
            with open(CONFIG_PATH, 'w') as f:
                json.dump(config, f, indent=4)
        except Exception:
            pass
        return jsonify({'success': True, 'message': 'Gemini API Key cleared.'})

@app.route('/api/copilot/generate-report', methods=['POST'])
@login_required
def api_copilot_generate_report():
    data = request.get_json() or {}
    node_id = data.get('node_id')
    
    if not node_id:
        return jsonify({'success': False, 'message': 'Missing node_id'}), 400
        
    summary = get_node_summary(node_id)
    if not summary or not summary['metrics']:
        return jsonify({'success': False, 'message': 'Telemetry metrics not found'}), 404
        
    decision = compute_decision_layer(node_id, summary['metrics'])
    narration = generate_narration("node_explain", summary, decision)
    
    # Generate filename
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"ai_incident_report_{node_id}_{timestamp}.pdf"
    file_path = os.path.join(REPORTS_DIR, filename)
    
    # Compile ReportLab PDF
    doc = SimpleDocTemplate(file_path, pagesize=letter, rightMargin=30, leftMargin=30, topMargin=105, bottomMargin=65)
    doc.incident_id = 'INC-1023'
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'RepTitle', parent=styles['Title'], fontName='Helvetica-Bold', fontSize=22, leading=26, textColor=colors.HexColor('#0f172a'), alignment=0, spaceAfter=20
    )
    h1_style = ParagraphStyle(
        'RepH1', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=14, leading=18, textColor=colors.HexColor('#1e3a8a'), spaceBefore=15, spaceAfter=10
    )
    body_style = ParagraphStyle(
        'RepBody', parent=styles['Normal'], fontName='Helvetica', fontSize=10, leading=14, textColor=colors.HexColor('#334155'), spaceAfter=8
    )
    
    story = []
    story.append(Paragraph(f"AI Cryptographic Incident Audit Report", title_style))
    story.append(Paragraph(f"Target Resource Node: <b>{node_id}</b>", body_style))
    story.append(Paragraph(f"Cloud Network Provider: {summary['metadata']['cloud_provider']} ({summary['metadata']['region']})", body_style))
    story.append(Paragraph(f"Private Host IP: {summary['metadata']['ip']} | Scan Date: {summary['metrics']['timestamp']}", body_style))
    story.append(Spacer(1, 15))
    
    story.append(Paragraph("1. Incident Summary & Narration", h1_style))
    # Replace markdown symbols for reportlab compatibility
    import re
    clean_narration = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', narration)
    clean_narration = clean_narration.replace('\n', '<br/>')
    story.append(Paragraph(clean_narration, body_style))
    
    story.append(Spacer(1, 15))
    story.append(Paragraph("2. Decision Control Layer Metrics", h1_style))
    story.append(Paragraph(f"<b>System Risk Score:</b> {decision['risk_score']:.1f}%", body_style))
    story.append(Paragraph(f"<b>Anomalous Severity Level:</b> {decision['severity']}", body_style))
    story.append(Paragraph(f"<b>Flagged Classifier Threat:</b> {decision['threat_type']}", body_style))
    
    story.append(Spacer(1, 15))
    story.append(Paragraph("3. Recommended Remediation Guidelines", h1_style))
    for idx, act in enumerate(decision['recommended_actions']):
        story.append(Paragraph(f"{idx+1}. <b>{act}</b>", body_style))
        
    doc.build(story, onFirstPage=draw_header_footer, onLaterPages=draw_header_footer)
    
    return jsonify({
        'success': True,
        'filename': filename,
        'message': f"PDF incident audit report successfully generated: {filename}"
    })

if __name__ == '__main__':
    # Start node simulator background process if not running
    # Checks for Reloader to prevent double spawning
    if not app.debug or os.environ.get("WERKZEUG_RUN_MAIN") == "true":
        try:
            print("[API] Starting background node simulator service...")
            subprocess.Popen([sys.executable, os.path.join(BASE_DIR, "node_simulator.py")])
        except Exception as e:
            print(f"[API] Error launching node_simulator.py subprocess: {e}")
            
    app.run(host='0.0.0.0', port=5000, debug=True)
